spring:
  profiles:
    active: dev

logging:
  level:
    com.horaoen.smart_safe_campus.dao: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.horaoen.smart_safe_campus.model

springdoc:
  packages-to-scan: com.horaoen.smart_safe_campus.api.v1