spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.horaoen.smart_safe_campus.dao: debug

mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.horaoen.smart_safe_campus.model
  config-location: classpath:config/mybatis-config.xml

springdoc:
  packages-to-scan: com.horaoen.smart_safe_campus.controller

security:
  jwt:
    secret: "!Q464rwr(&*)6%$#^%&JNJ46da"
    accessTokenExpireTime: PT2H
    refreshTokenExpireTime: PT8H


